### ISSUE TITLE
sass file globbing?

### ISSUE THREAD

**Issue by thedavidmeister** [Deraen/sass4clj#11]
I'd love to be able to use this, it looks like it would be great to be able to `watch` and `sass` with boot instead of having a ruby setup running in parallel in the project just for stylesheets.

The only thing holding me back is not being able to glob :(

https://github.com/chriseppstein/sass-globbing

Maybe I misunderstand, but there's already a custom `@import` setup in this project, so it wouldn't be crazy hard to add globbing?

**Comment by Deraen** [comment]
Hmm, interesting. Looks like this should be doable as the [Jsass Importer interface](https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/importer/Importer.java) allows to return multiple results from single import. Though I am not sure if that does what I think it does.

I don't have time to implement this myself now, but I can offer some pointers if you are interested in implementing this.
- What files should globs match?
  - Local files (Boot fileset / Lein source-dirs)?
  - Classpath resources?
  - Webjars?
  - I am thinking that local files are enough
- Would be good to use some existing glob library to handle most of stuff?
  - https://github.com/jkk/clj-glob seems out of date

**Comment by Deraen** [comment]
Looks like Java NIO includes file globbing implementation. 

https://docs.oracle.com/javase/tutorial/essential/io/find.html
http://javapapers.com/java/glob-with-java-nio/

**Comment by Deraen** [comment]
This has been debated a lot in Libsass and Sass issues:

https://github.com/sass/sass/issues/1517
https://github.com/sass/libsass/issues/156

I agree with the reasons there:

> No. Sass, like CSS, is an order-sensitive language, and glob-based imports make the ordering of imports unclear and fragile. This is a recipe for accidentally introducing subtle bugs that are hard to track down or even notice. - https://github.com/sass/sass/issues/1517#issuecomment-63137243

**Comment by thedavidmeister** [comment]
It's OK, I moved to Garden anyway and implemented a ns scanner sort of like clojure.test @Deraen thanks for looking into this.
