### ISSUE TITLE
Boot speak task compatibility

### ISSUE THREAD

**Issue by martinklepsch** [Deraen/sass4clj#13]
It would be nice if the boot task sets `boot.core/*warnings*` so the speak task picks those up. Also compilation errors should perhaps throw an exception?

Somewhat related: https://github.com/adzerk-oss/boot-reload/issues/72

**Comment by Deraen** [comment]
Currently warning messages are printed by default handler.

Will need to work out how to define custom warning handler: http://jsass.readthedocs.io/en/latest/functions.html#special-functions-warn-error-debug

**Comment by Deraen** [comment]
I implemented custom warning handler: https://github.com/Deraen/sass4clj/compare/warning-handler?expand=1

Unfortunately it can currently only access the warning message, not file path etc: https://github.com/bit3/jsass/issues/52

**Comment by Deraen** [comment]
Sass4clj can't handle warnings are they are directly written to stdout by libsass/jsass.

sass4clj should throw exceptions for errors.
