### ISSUE TITLE
It tries to compile anything it can lay its hands on

### ISSUE THREAD

**Issue by agzam** [Deraen/sass4clj#17]
If I for example have sass files that import mixins from a library in `npm` and I pull node_modules into fileset:

e.g: 

    (deftask add-node-modules []
      (with-pre-wrap fileset
	(let [nm (clojure.java.io/file "node_modules")]
	  (when-not (and (.exists nm) (.isDirectory nm))
	    (dosh "npm" "install"))
	  (-> fileset
	    (add-resource (clojure.java.io/file ".") :include #{#"^node_modules/"})
	    commit!))))

_thanks @anmonteiro_

boot-sass tries to compile things in node_modules. Definitely not something desired

**Comment by Deraen** [comment]
Both lein and boot tasks include "inputs" option to select only certain files to compile.
