### ISSUE TITLE
Attach to existing JVM?

### ISSUE THREAD

**Issue by vemv** [Deraen/sass4clj#20]
Hi there,

first of all thank you for sass4clj - it's a pleasure to see it working!

One downside vs. my previous setup (ruby-sass) is the RAM penalty of having a JVM around just for this (500mb in my machine).

I already have JVMs for Clojure(Script) processes, would it be possible to hack one's project.clj so whenever I run `lein figwheel`, the sass4clj library does its thing too?

I realise that this might be more of a generic leiningen question, but still I feel this would be a very commonly derisable thing, worth documenting.

Thoughts?

Cheers - Victor

**Comment by Deraen** [comment]
There is separate `sass4clj.api` for starting sass4clj in existing process. Readme also mentions configuration for shadow-cljs.

**Comment by vemv** [comment]
🍻!
