### ISSUE TITLE
File watching (sass4clj auto) only works for top-level stylesheets?

### ISSUE THREAD

**Issue by vemv** [Deraen/sass4clj#21]
Hi there,

our SCSS structure is the following:

![image](https://user-images.githubusercontent.com/1162994/28390937-4ebbc6fc-6cdc-11e7-9268-b1a9fde105a3.png)

Where `sass/themes/dark.scss` and `sass/themes/lite.scss` are the "top-level" stylesheets, everything else being dependencies of them.

This is reflected in our project.clj:

`:source-paths ["sass/themes"]`

This setup compiles correctly.

The problem is, if I edit any stylesheet that is not a top-level one, `sass4clj auto` will not detect the changes. I'd have to `touch` them manually (or with some script) for a recompile to be triggered.

Is this a bug in the `auto` implementation? Or maybe is our scss structure improvable?

Cheers - Victor

**Comment by Deraen** [comment]
Looks like the dependent files are outside of `:source-paths`. Only directories in `:source-paths` are watched for changes, so `:source-paths ["sass"]` should work.

If this wasn't the case, please comment and reopen.
