### ISSUE TITLE
In `api/build`, return status or throw when errors are encountered.

### ISSUE THREAD

**Issue by orestis** [Deraen/sass4clj#28]
Hi, thanks for maintaining this -- it's been very helpful to provide a smooth development experience!

I was wondering if you would considering returning a status report when errors are encountered. I'm calling `sass4clj.api/build`, and it swallows any exceptions thrown during the compilation. I'd like to plug in my own error reporting.

I'm working around this by using `with-out-str` and parsing the resulting text but surely that's a hack :)

I'm happy to submit a PR for this.

**Comment by Deraen** [comment]
At least partially solved by https://github.com/Deraen/sass4clj/commit/000cd218841ebf6c84be35aeb8de471617146102

**Comment by Deraen** [comment]
Now sass4clj.api/build should throw exceptions for errors. Warnings aren't handled by sass4clj, but are directly outputted to stdout by libsass/jsass.
