### ISSUE TITLE
Add support for specifying precision

### ISSUE THREAD

**Issue by djwhitt** [Deraen/sass4clj#3]
It looks like jsass defaults to 8 (https://github.com/bit3/jsass/blob/59e1f48422109adb6ef44756e43f5f20e42efa5e/src/main/java/io/bit3/jsass/Options.java#L57) which is actually enough for my needs currently, but I can easily imagine wanting to change it in the future.

**Comment by Deraen** [comment]
Do you know what other options are useful? I can quite easily add more options but I'm not using Sass myself and I don't know which options are useful.

http://jsass.readthedocs.org/en/latest/options.html

**Comment by djwhitt** [comment]
I'm relatively new to Sass myself, so I may not be the best person to ask. That said, I think an include paths option would likely be useful. Also, source maps, but I see you're tracking that in another issue.
