### ISSUE TITLE
Feature request: support for shadow-cljs

### ISSUE THREAD

**Issue by marharyta** [Deraen/sass4clj#34]
I was trying to find an easy solution for SASS-like syntax with ClojureScript for shadow-cljs but have not found it yet, but I think this could be fire if you could make your lib work with shadow-cljs. Thanks for the contribution though!

**Comment by Deraen** [comment]
I also answered this on Twitter.

https://shadow-cljs.github.io/docs/UsersGuide.html#_css_reloading

Shadow-cljs doesn't really have support for running any external tools, or downloading Java dependencies for other use than running Shadow-cljs itself. Instead you can use sass4clj like normal, with Lein or Clj, and point the CSS output to a folder Shadow-cljs is watching.

> shadow-cljs currently provides no support for directly compiling CSS but the usual tools will work and should be run separately. Just make sure the output is generated into the correct places.

Also, as you are already using npm with Shadow-cljs, you could as well run the regular sass tool: https://www.npmjs.com/package/sass It will be better supported, and the only benefit on sass4clj is the ability to load files from Java classpath (and not needing npm, when you aren't using it already).

**Comment by Deraen** [comment]
An approach integrating sass4clj watch with cljs compilation using Shadow CLJS clj-run task is now documented on the readme: https://github.com/Deraen/sass4clj#shadow-cljs-integration
