### ISSUE TITLE
libsass is deperecated

### ISSUE THREAD

**Issue by tomekw** [Deraen/sass4clj#35]
See: https://sass-lang.com/blog/libsass-is-deprecated

I presume there could be a CLJS library using the JS API: https://github.com/sass/dart-sass/blob/master/README.md#javascript-api

**Comment by Deraen** [comment]
The whole idea here is that sass4clj runs on JVM and can access classpath.

Looks like sass-embedded will allow custom importers (and thus accessing classpath) later.

Anyway, I don't think loading dependencies from classpath is that useful now. If one is using Shadow-cljs, it is easier to just use npm to load regular sass and dependecies.

I'l probably add notice to readme mentioning sass4clj is built on top of deprecated lib and recommend just using regular dart-sass from npm.

**Comment by tomekw** [comment]
Thanks! :)
