### ISSUE TITLE
Problem with relative imports

### ISSUE THREAD

**Issue by djwhitt** [Deraen/sass4clj#4]
Tried this:
1. Download contents of https://github.com/twbs/bootstrap-sass/tree/master/assets/stylesheets.
2. Copy to <resource-dir>/css/ in a boot based project using https://github.com/Deraen/boot-sass.
3. Add "import '@boostrap';" to app.scss.
4. Run "boot sass".

Results in this output:

```
Compiling {sass}... 77 changed files.
Error: file to import not found or unreadable: bootstrap/variables
       Current dir: 
        on line 8 of bootstrap
>> @import "bootstrap/variables";
   --------^
```

Moving the bootstrap directory up one level to the root of the resource path gets me this:

```
Compiling {sass}... 77 changed files.
Error: file to import not found or unreadable: mixins/hide-text
       Current dir: 
        on line 5 of mixins
>> @import "mixins/hide-text";
   --------^
```

So it gets passed the variables, but isn't able to locate the mixins sub-directory. It seems like it expects all imports to be relative to the root of the resource path.

**Comment by martinklepsch** [comment]
I created a [minimal repro](https://github.com/martinklepsch/sassclj-dotdot-issue) before discovering this issue. Maybe it helps in testing a solution. I'm ok with the resource-root-relative stuff for now :+1:

**Comment by Deraen** [comment]
This has been fixed, tested using latest snapshot and martin's repo:

```
boot -d deraen/boot-sass:0.3.0-SNAPSHOT -r sass sass target
```
