### ISSUE TITLE
Use Jsass 5

### ISSUE THREAD

**Issue by Deraen** [Deraen/sass4clj#6]
There are some API changes and just fixing the renamed calls didn't seem to be enough.

**Comment by kyptin** [comment]
Would it be possible to use jsass version 5.2.0 instead? I've been working with the jsass team (see bit3/jsass#42) to get jsass working with FreeBSD, and my PR just got merged as version 5.2.0.

If you'd rather I open a separate issue for 5.2.0 support, I'm happy to do that.

Also, let me know if you'd like help with this. I may be able to spend some time on it. Thanks!

**Comment by Deraen** [comment]
No need for another issue.

From 4 to 5 only error handling should have been changed: http://jsass.readthedocs.io/en/latest/changelog.html

Help would be very welcome. I'm not using Sass yet myself so improvements are very low priority for me, but if you have questions I can help with those.

**Comment by kyptin** [comment]
OK, I'll try to take a look soon and see what I can figure out. Cheers!

**Comment by Deraen** [comment]
https://github.com/Deraen/sass4clj/pull/16
